version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=library
      - POSTGRES_USER=iscrivera
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgresql-volume:/var/lib/postgresql/data
volumes: 
  postgresql-volume:
    external: true